---
title: "A study of smoking behaviors among adolescents"
author: 'CL'
date: "Dec 16, 2020"
abstract: |
  |   This study investigated the problem of smoking behaviors among adolescents based on the National Tobacco Survey of adolescents. The study mainly focused on two special hypotheses and applied formal statistical models to investigate the questions. It was found there is strong evidence shows the first time smoking age for males is younger than the first time smoking age for females. Also, it was found the likelihood of having used a electronic cigarettes is indeed significantlyt different between males and females
  |
  | **Keywords:**  first time smoking age; electronic cigarettes;
output:
  bookdown::pdf_document2:
toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,eval=TRUE, warning=F,message=F)
```

# Introduction

It is well known that children smoke more frequently in rural areas than in urban areas, and children smoke varies with different years old and different races. Also, it is claimed that there may be significant differences in smoking behaviors among young children in different states and regions. And for students in different schools, the smoking behaviors among young children may also vary from school to school. Under this background, the aim of this study is to investigate the problem of smoking behaviors among adolescents based on the National Tobacco Survey of adolescents. Particularly, some special hypotheses are made to be investigated as following:

1. Hypothesis 1: the first time smoking age for males is younger than the first time smoking age for females.

2. Hypothesis 2: the likelihood of having used a electronic cigarettes is different between males and females
 

This study would mainly focus on statistical models to answer the questions of interest. 



# Data 

The data source of this study comes from the 2014 American National Youth Tobacco Survey data. And it is restricted to the youngers with ages no less than 10 years old.  

More to be added.

# Models 

$$Y_{ijk}  \sim Bernoulli(\lambda_{ijk})$$
$$ logit( \lambda_{ijk} ) =  \mu + X_{ijk} \beta + U_i + Z_{ij}$$

* $Y_{ijk}$ is whether smoking for a student
* $\lambda_{ijk}$ is probability of smoking.
* $X_{ijk}$ are covariates: whether first time and smoking.
* $U_i$ and $Z_{ij}$ are random effects.

More to be added.

# Results

1. Hypothesis 1: the first time smoking age for males is younger than the first time smoking age for females.

The model shows that the first time smoking age for males is indeed younger than the first time smoking age for females significantly at 5% level.


2. Hypothesis 2: the likelihood of having used a electronic cigarettes is different between males and females
 
The model shows that the likelihood of having used a electronic cigarettes is different between males and females is indeed significantly at 5% level.

More to be added.

# Discussion and conclusion

More to be added.

# References

More to be added.

# Appendix 

More to be added.





